/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Service status. Without `deep` it reports the last probe (cheap enough for a
         *     container health check); with `deep=1` it probes every service again first.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description List the available profiles by reading <DATA_DIR>/<user>/profile.md.
         */
        get: operations["list_profiles_profiles_get"];
        put?: never;
        /**
         * Create Profile
         * @description Create a learner: <DATA_DIR>/<slug>/profile.md plus <lang>/USER.md.
         *
         *     The level is left empty on purpose: it is measured by the initial
         *     assessment, never guessed.
         */
        post: operations["create_profile_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Voices
         * @description Voices per language + speaking rates, for the frontend picker.
         */
        get: operations["list_voices_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Start */
        post: operations["session_start_session_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session End */
        post: operations["session_end_session_end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn */
        post: operations["turn_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/turn/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn Stream */
        post: operations["turn_stream_turn_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/read/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read Score */
        post: operations["read_score_read_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairs/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pairs Score */
        post: operations["pairs_score_pairs_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/{user}/{lang}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress */
        get: operations["get_progress_memory__user___lang__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/{user}/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress Dashboard */
        get: operations["progress_dashboard_progress__user___lang__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/srs/{user}/{lang}/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Srs Due */
        get: operations["srs_due_srs__user___lang__due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/srs/{user}/{lang}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Srs Review */
        post: operations["srs_review_srs__user___lang__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/srs/{user}/{lang}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Srs Sync */
        post: operations["srs_sync_srs__user___lang__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{user}/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stories List */
        get: operations["stories_list_stories__user___lang__get"];
        put?: never;
        /** Stories Create */
        post: operations["stories_create_stories__user___lang__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{user}/{lang}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stories Detail */
        get: operations["stories_detail_stories__user___lang___slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{user}/{lang}/{slug}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stories Next */
        post: operations["stories_next_stories__user___lang___slug__next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ocr Page
         * @description Return the page text so the learner can review it before starting the
         *     session (mode 3, 4 or 8). A local vision model can take tens of seconds.
         */
        post: operations["ocr_page_ocr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{user}/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Books List */
        get: operations["books_list_books__user___lang__get"];
        put?: never;
        /** Books Create */
        post: operations["books_create_books__user___lang__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{user}/{lang}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Books Detail */
        get: operations["books_detail_books__user___lang___slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestion/{user}/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home_suggestion__user___lang__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/syllabus/{user}/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Syllabus Overview */
        get: operations["syllabus_overview_syllabus__user___lang__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{user}/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions List */
        get: operations["sessions_list_sessions__user___lang__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{user}/{lang}/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Detail */
        get: operations["session_detail_sessions__user___lang___session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_ocr_page_ocr_post */
        Body_ocr_page_ocr_post: {
            /** User Id */
            user_id: string;
            /** Target Language */
            target_language: string;
            /** Image */
            image: string;
        };
        /** Body_pairs_score_pairs_score_post */
        Body_pairs_score_pairs_score_post: {
            /** Session Id */
            session_id: string;
            /** Pair Index */
            pair_index: number;
            /** Audio */
            audio: string;
        };
        /** Body_read_score_read_score_post */
        Body_read_score_read_score_post: {
            /** Session Id */
            session_id: string;
            /** Audio */
            audio?: string | null;
        };
        /** Body_turn_stream_turn_stream_post */
        Body_turn_stream_turn_stream_post: {
            /** Session Id */
            session_id: string;
            /** Text */
            text?: string | null;
            /** Audio */
            audio?: string | null;
            /**
             * Kickoff
             * @default false
             */
            kickoff: boolean;
            /** Speech Rate */
            speech_rate?: number | null;
        };
        /** Body_turn_turn_post */
        Body_turn_turn_post: {
            /** Session Id */
            session_id: string;
            /** Text */
            text?: string | null;
            /** Audio */
            audio?: string | null;
            /**
             * Action
             * @default talk
             */
            action: string;
            /** Speech Rate */
            speech_rate?: number | null;
        };
        /** BookCreateBody */
        BookCreateBody: {
            /** Title */
            title: string;
        };
        /** ChatStatus */
        ChatStatus: {
            /** Configured */
            configured: boolean;
            /** Reachable */
            reachable?: boolean | null;
            /** Detail */
            detail?: string | null;
            /** Vision */
            vision?: boolean | null;
        };
        /** Correction */
        Correction: {
            /**
             * Original
             * @default
             */
            original: string;
            /**
             * Corrected
             * @default
             */
            corrected: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResult */
        HealthResult: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            services: components["schemas"]["HealthServices"];
            /** Active Sessions */
            active_sessions: number;
        };
        /** HealthServices */
        HealthServices: {
            chat: components["schemas"]["ChatStatus"];
            stt: components["schemas"]["SpeechStatus"];
            tts: components["schemas"]["VoiceStatus"];
        };
        /** ProfileCreateReq */
        ProfileCreateReq: {
            /** Name */
            name: string;
            /** Target Language */
            target_language: string;
            /**
             * Goals
             * @default
             */
            goals: string;
            /**
             * Ui Language
             * @default en
             */
            ui_language: string;
        };
        /** ProgressData */
        ProgressData: {
            /** User */
            user: string;
            /** Lang */
            lang: string;
            /** Has Data */
            has_data: boolean;
            /**
             * Has Assessment
             * @default false
             */
            has_assessment: boolean;
            /** Cefr */
            cefr: string;
            /** Next Cefr */
            next_cefr?: string | null;
            /** Target Cefr */
            target_cefr?: string | null;
            /** Avg Score */
            avg_score: number;
            /** Levelup Eligible */
            levelup_eligible: boolean;
            /** Dims */
            dims: components["schemas"]["ProgressDim"][];
            /** Active Errors */
            active_errors: string[];
            /** Resolved Errors */
            resolved_errors: string[];
            /** Focus */
            focus: string;
            /** Milestones */
            milestones: string[];
            /** Weekly Reviews */
            weekly_reviews: components["schemas"]["WeeklyReview"][];
            /** Expressions Count */
            expressions_count: number;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["ProgressHistoryPoint"][];
            /** Updated */
            updated?: string | null;
        };
        /** ProgressDim */
        ProgressDim: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Score */
            score?: number | null;
        };
        /**
         * ProgressHistoryPoint
         * @description One point of the progress curve: date + the 8 scores + the note.
         */
        ProgressHistoryPoint: {
            /** Date */
            date: string;
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ReadScoreResult */
        ReadScoreResult: {
            /** Session Id */
            session_id: string;
            /** Heard Text */
            heard_text: string;
            /** Words */
            words: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Flagged */
            flagged: {
                [key: string]: unknown;
            }[];
        };
        /** SRSReviewBody */
        SRSReviewBody: {
            /** Term */
            term: string;
            /** Rating */
            rating: number;
        };
        /** SessionEndReq */
        SessionEndReq: {
            /** Session Id */
            session_id: string;
            /** End Page */
            end_page?: number | null;
        };
        /** SessionEndResult */
        SessionEndResult: {
            /** Closed */
            closed: string;
            /** Turns */
            turns: number;
        } & {
            [key: string]: unknown;
        };
        /** SessionStartReq */
        SessionStartReq: {
            /** User Id */
            user_id: string;
            /** Target Language */
            target_language: string;
            /**
             * Mode
             * @default 1
             */
            mode: number;
            /** Scenario */
            scenario?: string | null;
            /** Context */
            context?: string | null;
            /** Sub Mode */
            sub_mode?: string | null;
            /** Subject */
            subject?: string | null;
            /**
             * Generate
             * @default false
             */
            generate: boolean;
            /** Topic */
            topic?: string | null;
            /**
             * Defer Opening
             * @default false
             */
            defer_opening: boolean;
            /** Voice */
            voice?: string | null;
            /** Speech Rate */
            speech_rate?: number | null;
            /** Book Slug */
            book_slug?: string | null;
            /** Page */
            page?: number | null;
            /** Topic Id */
            topic_id?: string | null;
            /**
             * Pair Mode
             * @default false
             */
            pair_mode: boolean;
        };
        /** SessionStartResult */
        SessionStartResult: {
            /** Session Id */
            session_id: string;
            /** User */
            user: string;
            /** Target Language */
            target_language: string;
            /** Mode */
            mode: number;
            /** Scenario Info */
            scenario_info?: {
                [key: string]: unknown;
            } | null;
            opening?: components["schemas"]["TurnResult"] | null;
            /** Reference Text */
            reference_text?: string | null;
            /**
             * Weekly Review
             * @default false
             */
            weekly_review: boolean;
            /**
             * Opening Pending
             * @default false
             */
            opening_pending: boolean;
            /** Pairs */
            pairs?: unknown[] | null;
        };
        /** SpeechStatus */
        SpeechStatus: {
            /** Configured */
            configured: boolean;
            /** Reachable */
            reachable?: boolean | null;
            /** Detail */
            detail?: string | null;
            /** Word Timestamps */
            word_timestamps?: boolean | null;
        };
        /** StoryCreateBody */
        StoryCreateBody: {
            /** Topic */
            topic?: string | null;
        };
        /** TurnResult */
        TurnResult: {
            /** Session Id */
            session_id: string;
            /** Turn */
            turn: number;
            /** Transcript */
            transcript: string;
            /** Reply */
            reply: string;
            /** Corrections */
            corrections: components["schemas"]["Correction"][];
            /** New Vocab */
            new_vocab: components["schemas"]["VocabItem"][];
            /** Suggested Followup */
            suggested_followup: string;
            /**
             * Revised
             * @default
             */
            revised: string;
            /** Audio Url */
            audio_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VocabItem */
        VocabItem: {
            /** Term */
            term: string;
            /**
             * Translation
             * @default
             */
            translation: string;
            /**
             * Example
             * @default
             */
            example: string;
        };
        /** VoiceStatus */
        VoiceStatus: {
            /** Configured */
            configured: boolean;
            /** Reachable */
            reachable?: boolean | null;
            /** Detail */
            detail?: string | null;
            /** Languages */
            languages?: string[] | null;
        };
        /** WeeklyReview */
        WeeklyReview: {
            /** Week */
            week: string;
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: {
                deep?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_profile_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreateReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_voices_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    session_start_session_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionStartReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStartResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_end_session_end_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionEndReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEndResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turn_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_turn_turn_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turn_stream_turn_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_turn_stream_turn_stream_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_score_read_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_read_score_read_score_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadScoreResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pairs_score_pairs_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_pairs_score_pairs_score_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_memory__user___lang__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_dashboard_progress__user___lang__get: {
        parameters: {
            query?: {
                ui?: string | null;
            };
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    srs_due_srs__user___lang__due_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    srs_review_srs__user___lang__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SRSReviewBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    srs_sync_srs__user___lang__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stories_list_stories__user___lang__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stories_create_stories__user___lang__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StoryCreateBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stories_detail_stories__user___lang___slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stories_next_stories__user___lang___slug__next_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ocr_page_ocr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ocr_page_ocr_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    books_list_books__user___lang__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    books_create_books__user___lang__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    books_detail_books__user___lang___slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_suggestion__user___lang__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    syllabus_overview_syllabus__user___lang__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_list_sessions__user___lang__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_detail_sessions__user___lang___session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: string;
                lang: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
